---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: romm-cnpg
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"

spec:

  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.10

  backup:
    volumeSnapshot:
      className: csi-ceph-blockpool

  bootstrap:
    initdb:
      dataChecksums: true
      database: romm
      owner: romm
      encoding: "UTF8"
      localeCollate: en_US.utf8
      localeCType: en_US.utf8
    # recovery:
    #   database: romm
    #   owner: romm
    #   source: source

  # externalClusters:
  #   - name: source
  #     plugin:
  #       name: barman-cloud.cloudnative-pg.io
  #       parameters:
  #         barmanObjectName: romm

  # To be removed in a future release
  monitoring:
    enablePodMonitor: false

  # plugins:
  #   - name: barman-cloud.cloudnative-pg.io
  #     isWALArchiver: true
  #     parameters:
  #       barmanObjectName: romm

  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 256MB # amount of RAM to use for data caching, https://postgresqlco.nf/doc/en/param/shared_buffers/

  primaryUpdateStrategy: unsupervised # let k8s handle upgrades
  primaryUpdateMethod: restart # prefer downtime of image download from registry instead of switching primary instance (promote a standby instance to primary) when current primary pod is updated

  resources:
    requests:
      cpu: 1
      memory: 1024Mi
    limits:
      cpu: 2
      memory: 2048Mi

  storage:
    storageClass: ceph-block
    size: 5Gi

  walStorage:
    storageClass: ceph-block
    size: 5Gi
