---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-ingress-nginx-certificates
  namespace: flux-system
spec:
  interval: 15m
  path: "./kubernetes/apps/network/ingress-nginx/certificates"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-gitops
  wait: true
  postBuild:
    substituteFrom: []
  dependsOn:
    - name: cluster-apps-cert-manager-issuers
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-ingress-nginx-shared
  namespace: flux-system
spec:
  interval: 15m
  path: "./kubernetes/apps/network/ingress-nginx/shared"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-gitops
  wait: true
  postBuild:
    substituteFrom: []
  dependsOn:
    - name: cluster-apps-ingress-nginx-certificates
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-ingress-nginx-external
  namespace: flux-system
spec:
  interval: 15m
  path: "./kubernetes/apps/network/ingress-nginx/external"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-gitops
  wait: true
  postBuild:
    substituteFrom: []
  dependsOn:
    - name: cluster-apps-ingress-nginx-certificates
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-ingress-nginx-internal
  namespace: flux-system
spec:
  interval: 15m
  path: "./kubernetes/apps/network/ingress-nginx/internal"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-gitops
  wait: true
  postBuild:
    substituteFrom: []
  dependsOn:
    - name: cluster-apps-ingress-nginx-certificates
