---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-home-assistant
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
    secret.reloader.stakater.com/reload: pg-home-assistant-cnpg-secret

spec:

  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.10

  backup:
    volumeSnapshot:
      className: csi-ceph-blockpool

  bootstrap:
    # initdb:
    #   dataChecksums: true
    #   database: home-assistant
    #   owner: home-assistant
    #   encoding: "UTF8"
    #   localeCollate: en_US.utf8
    #   localeCType: en_US.utf8
    recovery:
      database: home-assistant
      owner: home-assistant
      source: source

  externalClusters:
    - name: source
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: home-assistant

  # To be removed in a future release
  monitoring:
    enablePodMonitor: false

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: home-assistant

  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 256MB # amount of RAM to use for data caching, https://postgresqlco.nf/doc/en/param/shared_buffers/

  primaryUpdateStrategy: unsupervised # let k8s handle upgrades
  primaryUpdateMethod: restart # prefer downtime of image download from registry instead of switching primary instance (promote a standby instance to primary) when current primary pod is updated

  resources:
    requests:
      cpu: 250m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 512Mi

  storage:
    size: 25Gi
    storageClass: ceph-block

  walStorage:
    storageClass: ceph-block
    size: 25Gi

#  # RECOVERY
#  bootstrap:
#    recovery:
#      source: &previous-cluster pg-home-assistant-v0
#  ## Note: externalClusters is needed when recovering from an existing cnpg cluster
#  externalClusters:
#    - name: *previous-cluster
#      barmanObjectStore:
#        wal:
#          compression: gzip
#          maxParallel: 8
#        destinationPath: s3://cnpg/
#        endpointURL: http://minio.internal:9000
#        s3Credentials:
#          accessKeyId:
#            name: pg-home-assistant-cnpg-secret
#            key: AWS_ACCESS_KEY_ID
#          secretAccessKey:
#            name: pg-home-assistant-cnpg-secret
#            key: AWS_SECRET_ACCESS_KEY


