---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-batch-demo-2
  annotations:
    secret.reloader.stakater.com/reload: pg-batch-demo-2-cnpg-secret

spec:

  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6-31
  primaryUpdateStrategy: unsupervised # let k8s handle upgrades
  primaryUpdateMethod: restart # prefer downtime of image download from registry instead of switching primary instance (promote a standby instance to primary) when current primary pod is updated

  resources:
    requests:
      memory: 1024Mi
      cpu: 250m
    limits:
      memory: 2048Mi
      cpu: 1000m

  storage:
    storageClass: ceph-block
    size: 1Gi

  walStorage:
    storageClass: ceph-block
    size: 1Gi

  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 256MB # amount of RAM to use for data caching, https://postgresqlco.nf/doc/en/param/shared_buffers/

  monitoring:
    enablePodMonitor: true
  # configured according to below link to allow customizing of initdb via Flux
  # https://cloudnative-pg.io/documentation/1.20/bootstrap/#configure-the-application-database

  bootstrap:
    initdb:
      dataChecksums: true
      database: batch-demo-2
      owner: batch-demo-2
      encoding: "UTF8"
      localeCollate: en_US.utf8
      localeCType: en_US.utf8

  backup:
    retentionPolicy: 30d
    volumeSnapshot:
      className: ceph-block
    barmanObjectStore:
      destinationPath: s3://cnpg/
      endpointURL: http://minio.internal:9000
      s3Credentials:
        accessKeyId:
          name: pg-batch-demo-2-cnpg-secret
          key: AWS_SECRET_ACCESS_KEY_ID
        secretAccessKey:
          name: pg-batch-demo-2-cnpg-secret
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
        maxParallel: 8

#  # RECOVERY
#  bootstrap:
#    recovery:
          #      source: &previous-cluster pg-batch-demo-2-v0
#  ## Note: externalClusters is needed when recovering from an existing cnpg cluster
#  externalClusters:
#    - name: *previous-cluster
#      barmanObjectStore:
#        wal:
#          compression: bzip2
#          maxParallel: 8
#        destinationPath: s3://cnpg/
          #        endpointURL: http://minio.internal:9000
#        s3Credentials:
#          accessKeyId:
#            name: pg-batch-demo-2-cnpg-secret
#            key: AWS_ACCESS_KEY_ID
#          secretAccessKey:
#            name: cpg-batch-demo-2-cnpg-secret
#            key: AWS_SECRET_ACCESS_KEY

