---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: oci-terraform-readarr
  namespace: flux-system
spec:
  interval: 1m
  url: oci://ghcr.io/dmfrey/terraform/readarr
  ref:
    tag: main
