---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: oci-terraform-authentik
spec:
  interval: 1h
  url: oci://ghcr.io/dmfrey/terraform/authentik
  ref:
    tag: main
