---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pinepods
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: pinepods-secret
    template:
      engineVersion: v2
      data:
        USERNAME: "{{ .PINEPODS_ADMIN_USERNAME }}"
        PASSWORD: "{{ .PINEPODS_ADMIN_PASSWORD }}"
        FULLNAME: "{{ .PINEPODS_ADMIN_FULLNAME }}"
        EMAIL: "{{ .PINEPODS_ADMIN_EMAIL }}"
        OIDC_PROVIDER_NAME: "Authentik"
        OIDC_CLIENT_ID: "{{ .AUTHENTIK_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .AUTHENTIK_CLIENT_SECRET }}"
        OIDC_AUTHORIZATION_URL: "https://auth.dmfrey.com/application/o/authorize/"
        OIDC_TOKEN_URL: "https://auth.dmfrey.com/application/o/token/"
        OIDC_USER_INFO_URL: "https://auth.dmfrey.com/application/o/userinfo/"
        OIDC_SCOPE: "openid profile email"
        OIDC_BUTTON_TEXT: "Sign in with Authentik"
        OIDC_ROLES_CLAIM: "groups"
        OIDC_USER_ROLE: "Users"
        OIDC_ADMIN_ROLE: "authentik Admins"
        OIDC_DISABLE_STANDARD_LOGIN: "false"
  dataFrom:
  - extract:
      key: pinepods