---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openweb-dragonflydb-s3
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: openweb-dragonflydb-s3-secret
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .DRAONGFLYDB_AWS_SECRET_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .DRAONGFLYDB_AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
  - extract:
      key: dragonflydb
