---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: affine
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: affine-secret
    template:
      engineVersion: v2
      data:
        AFFINE_OIDC_CLIENT_ID: "{{ .AUTHENTIK_CLIENT_ID }}"
        AFFINE_OIDC_CLIENT_SECRET: "{{ .AUTHENTIK_CLIENT_SECRET }}"
  dataFrom:
  - extract:
      key: affine
