---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: soularr
spec:
  # components:
  #   - ../../../../components/volsync
  # dependsOn:
  #   - name: rook-ceph-cluster
  #     namespace: rook-ceph
  #   - name: volsync
  #     namespace: volsync-system
  interval: 1h
  path: "./kubernetes/homelab-k8s-001/apps/download/soularr/app"
  # postBuild:
  #   substitute:
  #     APP: soularr
  #     VOLSYNC_CLAIM: sonarr-config
  #     VOLSYNC_CAPACITY: 1Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: download
