---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  ORGANIZATION: frey
  CLUSTER_NAME: homelab-k8s-001
  CLUSTER_APISERVER_ENDPOINT: 192.168.30.20
  DNS_ADDR: 192.168.30.10
  QNAP_ADDR: 192.168.30.5

  SVC_BLOCKY_ADDR: 192.168.30.10
  SVC_GATEWAY_ADDR: 192.168.30.100
  SVC_NEXUS_ADDR: 192.168.30.150
  SVC_EXTERNAL_NGINX_ADDR: 192.168.30.200
  SVC_INTERNAL_NGINX_ADDR: 192.168.30.201
  SVC_OLLAMA_ADDR: 192.168.30.241
  SVC_HASS_ADDR: 192.168.30.242
  SVC_MATTER_ADDR: 192.168.30.243
  SVC_GO2RTC_ADDR: 192.168.30.244
  SVC_MQTT_ADDR: 192.168.30.247
  SVC_PLEX_ADDR: 192.168.30.227
  SVC_JELLYFIN_ADDR: 192.168.30.228
  SVC_VPN_ADDR: 192.168.30.77
  SVC_SMTP_RELAY_ADDR: 192.168.30.225
  SVC_SYSLOG_ADDR: 192.168.30.210
  WHITELIST_IP_RANGE: "192.168.30.0/24, 192.168.31.0/24, 172.22.0.0/15"

  TIMEZONE: "America/New_York"

  BITWARDEN_CABUNDLE: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ5akNDQVhDZ0F3SUJBZ0lRWGE0a3FqYVNWK2FzaHRUY3lwM3diREFLQmdncWhrak9QUVFEQWpBMk1Rc3cKQ1FZRFZRUUdFd0pWVXpFVU1CSUdBMVVFQ2hNTGFHOXRaV3hoWWpVM05qY3hFVEFQQmdOVkJBc1RDRWx1ZEdWeQpibUZzTUI0WERUSTBNVEF4TXpFek5UazBPRm9YRFRJMU1ERXhNVEV6TlRrME9Gb3dOakVMTUFrR0ExVUVCaE1DClZWTXhGREFTQmdOVkJBb1RDMmh2YldWc1lXSTFOelkzTVJFd0R3WURWUVFMRXdoSmJuUmxjbTVoYkRCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJLaEZrc2pFeXU4cWN2RUc5aGVsRHE5bEdMdkU5M2M3U1RveQpKL0E1SmJVUUY5dWJLYTlJZC9CY1pRY21wVXdLSkd2Nk1nSk1kVE1PUURJb08wdk1wNHVqWURCZU1BNEdBMVVkCkR3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU0tYanNjZXVaZHJiYVUKMTVoNTFEN09XQUJreGpBY0JnTlZIUkVFRlRBVGdoRm9iMjFsYkdGaUxtWnlaWGt1YUc5dFpUQUtCZ2dxaGtqTwpQUVFEQWdOSUFEQkZBaUJFVjBtOG91cWZEd2U3cVJhOEJnUlRueWV3Zk40RCtwSFVna0JZZTZLQnBnSWhBT1pNCkdhM0RldmlIaTdRVGhXOENjUjRNUW1mMVVITzhmVGpnN01SeHJSbmcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
