---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/kustomize.toolkit.fluxcd.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

components:
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./bazarr/ks.yaml
  - ./jellyfin/ks.yaml
  - ./jellyplex-watched/ks.yaml
  - ./lidarr/ks.yaml
  - ./music-assistant/ks.yaml
  - ./overseerr/ks.yaml
  - ./pinepods/ks.yaml
  - ./plex/ks.yaml
  - ./plex-meta-manager/ks.yaml
  - ./radarr/ks.yaml
  - ./recyclarr/ks.yaml
  # - ./romm/ks.yaml
  - ./sonarr/ks.yaml
  - ./tautulli/ks.yaml
  - ./unpackerr/ks.yaml
  - ./wizarr/ks.yaml

  # - ./soularr/ks.yaml
