apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: home
stringData:
    ZIGBEE2MQTT_CONFIG_ADVANCED_CHANNEL: ENC[AES256_GCM,data:XfY=,iv:xElUYn5Jxp3hh6Zm4sCRlwEmxNAMVISQ8ZDwnXOo5Gc=,tag:l+mMBjPV2W52KY2ZTKfamg==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:f1dVp5MmrTL2OxM9fxVUg4WNwCRzbaeoQK2R/Ztx,iv:qeGQcWYHEg1fKsY7AzUW49m7P0MOtYJFQFq8k0UI5L4=,tag:kR/ppgS+awtP7DoNsUB8PQ==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:zaucD7Q=,iv:Ls7bZxShvwBKignu24eLc64W8B6HRfof0m4weug/U24=,tag:l2HOZn9abP0KPtzJ1wHFqA==,type:int]
    ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:BXypLMe9+66LWRRb42NHo3A+ff7wrApZ2Jofgh6Wjz5VnhJqYhUtky7+smAz7av0DXl2AEQlVKc=,iv:TdEQxPO9nLS/qTbDkDOYQ2zT0xJpjAjpO3PK/Gk5yN4=,tag:BY9Peu5ysSKLGXEvuu7Zhw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/homelab5767/locations/global/keyRings/homelab5767-keyring/cryptoKeys/sops
          created_at: "2023-10-30T14:20:29Z"
          enc: CiQAwGzpTgVMpjdKSBqfHvjXnvC4XrZWAQLHzH/hoHdlmSDdC0ASSQCiPSpDzx3ewHFR7+VQ1rqq1hL9sUPWTEW93jK5m1FGom6/UHRDogb58JgHOxrdxf/PiuN7qS0p/qbmFZHXe5FPcQGFbnpB0uo=
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19tytvakhpucnqygj898axa8v5uw86uhr0eld7s89uqka737c23msw54kpr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4d1RBcDI1UkgxSnhDaFcx
            QVdFNGxxbm4rMGYwdXV4RU9NV3lmOHdWd0h3CjJrZEtUczJpb2FyeWlOTFJ1OHd6
            NEwvay9nS3pqR3RCN2lZRmdZWUlZRmMKLS0tIEpCUjdVSjBTdDJHT3dzNURqZytJ
            YmtZUjN5K29VM1RGOUpVZmJPM3FYRVEKO1WxTXiT7+CQbHcdZ6DsDsrSAMMfLjdj
            hx9xFqCRX+L5VNa1LO3rxNENgI5h5UMEygb67vfK2WJhtYfYeJVU/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-31T15:46:46Z"
    mac: ENC[AES256_GCM,data:WVkCSa3sNqMAQI00lISH9VwikJ0fzzIrsdF9sVYL0Yiu5utaxI0tC+/8bIXgYezmfAZsZHL6myreZDFlkQYzTFWG9baTe0XEMttPiVnV6286PlXd2tZVgWia5g3U12GH19x9XjzhGFPlTJjl5kzcBu4NBnH3TS/9gpZGGc0Rx1c=,iv:85OY1DqtrqZpT/yDFhVQZCDjUqo7TN0duWgsaCpb0uA=,tag:7+G3+GejwQAD04GD1zcOZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
