---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/kustomize.toolkit.fluxcd.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./cnpg-cluster.yaml
  - ./objectstore.yaml
  - ./podmonitor.yaml
  - ./scheduledbackup.yaml
  - ./externalsecret.yaml

