# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/kustomize.toolkit.fluxcd.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system

helmCharts:
- name: kubelet-csr-approver
  repo: https://postfinance.github.io/kubelet-csr-approver
  version: 1.1.0
  releaseName: kubelet-csr-approver
  namespace: system
  valuesFile: values.yaml
  
commonAnnotations:
  meta.helm.sh/release-name: kubelet-csr-approver
  meta.helm.sh/release-namespace: system
commonLabels:
  app.kubernetes.io/managed-by: Helm
