---
# yaml-language-server: $schema=https://kubernetes-schemas-5e0.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph

spec:

  interval: 15m

  releaseName: rook-ceph
  chart:
    spec:
      chart: rook-ceph
      version: v1.16.3
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system

  driftDetection:
    mode: enabled

  values:

    crds:
      enabled: true

    image:
      repository: rook/ceph

    csi:
      # provisioner:
      #   image:
      #     repository: registry.k8s.io/sig-storage/csi-provisioner
      #     tag: v5.1.0

      enableVolumeGroupSnapshot: false # TODO: enable this when v1beta1 CRDs are available

      cephFSKernelMountOptions: ms_mode=prefer-crc
      enableLiveness: true
      serviceMonitor:
        enabled: true

      # kubeletDirPath: /var/lib/kubelet
      # enableCSIHostNetwork: true
      # pluginTolerations:
      #   - effect: "NoExecute"
      #     operator: "Exists"
      #   - effect: "NoSchedule"
      #     operator: "Exists"

      # csiRBDProvisionerResource: |
      #   - name : csi-provisioner
      #     resource:
      #       requests:
      #         memory: 128Mi
      #         cpu: 25m
      #       limits:
      #         memory: 256Mi
      #   - name : csi-resizer
      #     resource:
      #       requests:
      #         memory: 128Mi
      #         cpu: 25m
      #       limits:
      #         memory: 256Mi
      #   - name : csi-attacher
      #     resource:
      #       requests:
      #         memory: 128Mi
      #         cpu: 25m
      #       limits:
      #         memory: 256Mi
      #   - name : csi-snapshotter
      #     resource:
      #       requests:
      #         memory: 128Mi
      #         cpu: 25m
      #       limits:
      #         memory: 256Mi
      #   - name : csi-rbdplugin
      #     resource:
      #       requests:
      #         memory: 512Mi
      #         cpu: 50m
      #       limits:
      #         memory: 1Gi
      #   - name : csi-omap-generator
      #     resource:
      #       requests:
      #         memory: 512Mi
      #         cpu: 50m
      #       limits:
      #         memory: 1Gi
      #   - name : liveness-prometheus
      #     resource:
      #       requests:
      #         memory: 128Mi
      #         cpu: 25m
      #       limits:
      #         memory: 256Mi

      # csiCephFSProvisionerResource: |
      #   - name : csi-provisioner
      #     resource:
      #       requests:
      #         memory: 128Mi
      #         cpu: 25m
      #       limits:
      #         memory: 256Mi
      #   - name : csi-resizer
      #     resource:
      #       requests:
      #         memory: 128Mi
      #         cpu: 25m
      #       limits:
      #         memory: 256Mi
      #   - name : csi-attacher
      #     resource:
      #       requests:
      #         memory: 128Mi
      #         cpu: 25m
      #       limits:
      #         memory: 256Mi
      #   - name : csi-snapshotter
      #     resource:
      #       requests:
      #         memory: 128Mi
      #         cpu: 25m
      #       limits:
      #         memory: 256Mi
      #   - name : csi-cephfsplugin
      #     resource:
      #       requests:
      #         memory: 512Mi
      #         cpu: 50m
      #       limits:
      #         memory: 1Gi
      #   - name : liveness-prometheus
      #     resource:
      #       requests:
      #         memory: 128Mi
      #         cpu: 25m
      #       limits:
      #         memory: 256Mi

    enableDiscoveryDaemon: true

    monitoring:
      enabled: true

    # pspEnable: false

    resources:
      requests:
        cpu: 109m
        memory: 204M
      limits:
        memory: 453M
