---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/kustomize.toolkit.fluxcd.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./barman-objectstore.yaml
  - ./cnpg-podmonitor.yaml
  - ./cnpg-scheduledbackup.yaml
  - ./externalsecret.yaml
  - ./pgcluster.yaml
