---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pg-affine
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: pg-affine
  podMetricsEndpoints:
  - port: metrics
