---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: openweb-kopia
spec:
  sourcePVC: openweb
  trigger:
    manual: "initial-backup-2026-02-03T15:34:00-01"
  kopia:
    accessModes:
      - ReadWriteOnce
    compression: zstd-fastest
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
    repository: openweb-volsync-secret
    parallelism: 2
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      hourly: 24
      daily: 7
