---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: lidarr-provisioner
  namespace: media
spec:
  
  interval: 15m
  path: "./"
    
  approvePlan: auto
  
  sourceRef:
    kind: OCIRepository
    name: oci-terraform-lidarr
    namespace: flux-system
  
  writeOutputsToSecret:
    name: lidarr-tfstate
  
  varsFrom:
    - kind: Secret
      name: starr-apps-secret
    - kind: Secret
      name: sabnzbd-secret
